# Generated by Django 4.1.7 on 2023-03-25 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochody',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rok_produkcji', models.IntegerField()),
                ('nr_rejestracyjny', models.CharField(max_length=20)),
                ('pojemność_silnika', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wydatki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('opis', models.TextField()),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.samochody')),
            ],
        ),
        migrations.CreateModel(
            name='Tankowania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('przebieg', models.IntegerField()),
                ('ilość_paliwa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cena_za_litr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.samochody')),
            ],
        ),
        migrations.CreateModel(
            name='Przebiegi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('przebieg', models.IntegerField()),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.samochody')),
            ],
        ),
        migrations.CreateModel(
            name='Naprawy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('opis', models.TextField()),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.samochody')),
            ],
        ),
    ]
